//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilety
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BiletyEntities : DbContext
    {
        public BiletyEntities()
            : base("name=BiletyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Bilety> Bilety { get; set; }
        public virtual DbSet<Miejsca> Miejsca { get; set; }
        public virtual DbSet<Transakcje> Transakcje { get; set; }
        public virtual DbSet<Wydarzenia> Wydarzenia { get; set; }
    
        public virtual ObjectResult<Podsumowanie_Result> Podsumowanie(Nullable<int> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Podsumowanie_Result>("Podsumowanie", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PokazCeny()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PokazCeny");
        }
    
        public virtual ObjectResult<string> WyswietlPrzeciwnika(Nullable<int> idwyd)
        {
            var idwydParameter = idwyd.HasValue ?
                new ObjectParameter("idwyd", idwyd) :
                new ObjectParameter("idwyd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WyswietlPrzeciwnika", idwydParameter);
        }
    
        public virtual ObjectResult<WyswietlWydarzenia_Result> WyswietlWydarzenia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WyswietlWydarzenia_Result>("WyswietlWydarzenia");
        }
    }
}
