//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilety()
        {
            this.Transakcje = new HashSet<Transakcje>();
        }
    
        public int IdBiletu { get; set; }
        public int IdMiejsca { get; set; }
        public string Przeciwnik { get; set; }
        public int IdWydarzenia { get; set; }
    
        public virtual Miejsca Miejsca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcje> Transakcje { get; set; }
        public virtual Wydarzenia Wydarzenia { get; set; }
    }
}
