//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miejsca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miejsca()
        {
            this.Bilety1 = new HashSet<Bilety>();
        }
    
        public int IdMiejsca { get; set; }
        public string Sektor { get; set; }
        public decimal Cena { get; set; }
        public int Ile_Miejsc { get; set; }
        public int IdWydarzenia { get; set; }
    
        public virtual Wydarzenia Wydarzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilety> Bilety1 { get; set; }
    }
}
