//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilety
{
    using System;
    
    public partial class PokazCeny_Result1
    {
        public string Sektor { get; set; }
        public decimal Cena { get; set; }
        public int Ile_Miejsc { get; set; }
    }
}
